name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build  # Assumes you have a build script in your package.json

    - name: Run tests
      run: npm test  # Assumes you have tests defined in your package.json